[package]
name = "bili-tools"
version = "0.1.0"
edition = "2024"

[dependencies]
# 用于异步时和网络请求
tokio = { vserion = "1.0", features = ["full"] }
reqwest = { vserion = "0.11", features = ["json", "cookies"] }

# 序列化和反序列化
serde = { version = "1.0", features = ["derives"] }

# 错误处理
thiserror = "1.0"

# 命令行解析
clap = { version = "4.0", features = ["derives"] }

# 二维码和加密工具
qrcode = "0.12"
md5 = "0.7"
